---
- name: Installation et configuration de Docker sur Ubuntu 22.04
  hosts: all
  become: yes
  tasks:
    - name: Mise à jour des paquets
      apt:
        update_cache: yes

    - name: Installation de Docker (avec -y pour éviter la confirmation)
      command: sudo apt install docker.io -y
      changed_when: true

    - name: Activer Docker au démarrage
      systemd:
        name: docker
        enabled: yes

    - name: Démarrer Docker
      systemd:
        name: docker
        state: started

    - name: Vérifier le statut de Docker
      command: sudo systemctl status docker
      register: docker_status
      changed_when: false

    - name: Afficher le statut du service Docker
      debug:
        msg: "{{ docker_status.stdout_lines }}"

