---
- name: Install and configure Docker on Ubuntu 22.04
  hosts: all
  become: yes
  tasks:
    - name: Update packages
      apt:
        update_cache: yes

    - name: Install Docker (with -y to avoid confirmation)
      command: sudo apt install docker.io -y
      changed_when: true

    - name: Enable Docker to start on boot
      systemd:
        name: docker
        enabled: yes

    - name: Start Docker
      systemd:
        name: docker
        state: started

    - name: Check Docker status
      command: sudo systemctl status docker
      register: docker_status
      changed_when: false

    - name: Display Docker service status
      debug:
        msg: "{{ docker_status.stdout_lines }}"

